version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - './client:/app'
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - '/app/node_modules'
      - './server:/app'
